### ISSUE TITLE
[Bug] Utilities.getComponentDescription()

### ISSUE THREAD

**Issue by darkclif** [PawelAdamczuk/APCC#1]
Utilities.getComponentDescription(int id)
1. Nie wypisuje parametrów które są ustawione lecz nie wypełnione.
2. Nie kontynuuje wypisywania kolejnych wypełnionych parametrów kiedy napotka niewypełniony parametr.

Proponuje żeby wypisywał "-" jeżeli parametr jest nieustawiony.

![2016-05-26 14_59_13-apcc](https://cloud.githubusercontent.com/assets/2838604/15575339/944ab612-2352-11e6-8c62-76981b2a0dad.png)

**Comment by PawelAdamczuk** [comment]
Fixed.
